#!/usr/bin/env bash
set -euo pipefail

SCRIPT_PATH="${BASH_SOURCE[0]}"
while [[ -L "$SCRIPT_PATH" ]]; do
  SCRIPT_LINK_DIR="$(cd "$(dirname "$SCRIPT_PATH")" && pwd)"
  SCRIPT_PATH="$(readlink "$SCRIPT_PATH")"
  [[ "$SCRIPT_PATH" == /* ]] || SCRIPT_PATH="$SCRIPT_LINK_DIR/$SCRIPT_PATH"
done
SCRIPT_DIR="$(cd "$(dirname "$SCRIPT_PATH")" && pwd)"
# shellcheck disable=SC1091
source "$SCRIPT_DIR/lib.sh"

WINDOWS_USER=""
DROPBOX_HOME=""
LOCAL_ROOT_VALUE="/mnt/d/ResearchLocal"

usage() {
  cat <<'USAGE'
Usage:
  setup-machine.sh [options]

Options:
  --windows-user NAME    Windows account name
  --dropbox-home PATH    Dropbox root as seen from WSL
  --local-root PATH      PC-local large-data root (default: /mnt/d/ResearchLocal)
  -h, --help             Show this help
USAGE
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --windows-user)
      [[ $# -ge 2 ]] || fail "--windows-user requires a value"
      WINDOWS_USER="$2"
      shift 2
      ;;
    --dropbox-home)
      [[ $# -ge 2 ]] || fail "--dropbox-home requires a value"
      DROPBOX_HOME="$2"
      shift 2
      ;;
    --local-root)
      [[ $# -ge 2 ]] || fail "--local-root requires a value"
      LOCAL_ROOT_VALUE="$2"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      fail "Unknown option: $1"
      ;;
  esac
done

if [[ -z "$WINDOWS_USER" ]] && command -v cmd.exe >/dev/null 2>&1; then
  WINDOWS_USER="$(cmd.exe /C 'echo %USERNAME%' 2>/dev/null | tr -d '\r' | tail -n 1)"
fi

if [[ -z "$DROPBOX_HOME" ]]; then
  [[ -n "$WINDOWS_USER" ]] || fail "Could not detect the Windows user. Use --windows-user or --dropbox-home."
  DROPBOX_HOME="/mnt/c/Users/$WINDOWS_USER/Dropbox"
fi

RESEARCH_SOURCE="$DROPBOX_HOME/Research"
LARGE_SOURCE="$DROPBOX_HOME/ForShareLargeData"

[[ -d "$RESEARCH_SOURCE" ]] || fail "Dropbox Research directory was not found: $RESEARCH_SOURCE"
[[ -d "$LARGE_SOURCE" ]] || fail "Dropbox ForShareLargeData directory was not found: $LARGE_SOURCE"

mkdir -p "$HOME/src" "$HOME/worktrees" "$HOME/scratch" "$HOME/data-roots" "$HOME/.local/bin"
mkdir -p "$LOCAL_ROOT_VALUE"

ln -sfnT "$RESEARCH_SOURCE" "$HOME/data-roots/Research"
ln -sfnT "$LARGE_SOURCE" "$HOME/data-roots/ForShareLargeData"
ln -sfnT "$LOCAL_ROOT_VALUE" "$HOME/data-roots/LocalLarge"

cat > "$HOME/.research_env" <<EOF_ENV
# Generated by research-dev-infra/scripts/setup-machine.sh
export RESEARCH_ROOT="\$HOME/data-roots/Research"
export LARGE_ROOT="\$HOME/data-roots/ForShareLargeData"
export LOCAL_ROOT="\$HOME/data-roots/LocalLarge"
export SRC_ROOT="\$HOME/src"
export WORKTREE_ROOT="\$HOME/worktrees"
export SCRATCH_ROOT="\$HOME/scratch"
EOF_ENV

BASHRC_LINE='[ -f "$HOME/.research_env" ] && source "$HOME/.research_env"'
if ! grep -Fqx "$BASHRC_LINE" "$HOME/.bashrc" 2>/dev/null; then
  printf '\n%s\n' "$BASHRC_LINE" >> "$HOME/.bashrc"
fi

ln -sfnT "$INFRA_ROOT/scripts/new-project.sh" "$HOME/.local/bin/new-project"
ln -sfnT "$INFRA_ROOT/scripts/new-worktree.sh" "$HOME/.local/bin/new-worktree"
ln -sfnT "$INFRA_ROOT/scripts/remove-worktree.sh" "$HOME/.local/bin/remove-worktree"
ln -sfnT "$INFRA_ROOT/scripts/setup-project-links.sh" "$HOME/.local/bin/setup-project-links"
ln -sfnT "$INFRA_ROOT/scripts/doctor.sh" "$HOME/.local/bin/research-doctor"
ln -sfnT "$INFRA_ROOT/scripts/install-agents.sh" "$HOME/.local/bin/install-coding-agents"
ln -sfnT "$INFRA_ROOT/scripts/install-miniforge.sh" "$HOME/.local/bin/install-miniforge"
ln -sfnT "$INFRA_ROOT/scripts/analysis-smoke-test.sh" "$HOME/.local/bin/analysis-smoke-test"

PATH_LINE='export PATH="$HOME/.local/bin:$PATH"'
if ! grep -Fqx "$PATH_LINE" "$HOME/.bashrc" 2>/dev/null; then
  printf '%s\n' "$PATH_LINE" >> "$HOME/.bashrc"
fi

info "Machine setup completed"
echo "  Dropbox Research:          $RESEARCH_SOURCE"
echo "  Dropbox ForShareLargeData: $LARGE_SOURCE"
echo "  LocalLarge:                $LOCAL_ROOT_VALUE"
echo "  Environment file:          $HOME/.research_env"
echo
echo "Run: source ~/.bashrc"
echo "Then: research-doctor"
