#!/usr/bin/env bash
set -euo pipefail

SCRIPT_PATH="${BASH_SOURCE[0]}"
while [[ -L "$SCRIPT_PATH" ]]; do
  SCRIPT_LINK_DIR="$(cd "$(dirname "$SCRIPT_PATH")" && pwd)"
  SCRIPT_PATH="$(readlink "$SCRIPT_PATH")"
  [[ "$SCRIPT_PATH" == /* ]] || SCRIPT_PATH="$SCRIPT_LINK_DIR/$SCRIPT_PATH"
done
SCRIPT_DIR="$(cd "$(dirname "$SCRIPT_PATH")" && pwd)"
# shellcheck disable=SC1091
source "$SCRIPT_DIR/lib.sh"

WINDOWS_USER=""
DROPBOX_HOME=""

usage() {
  cat <<'USAGE'
Usage:
  setup-machine.sh [options]

Options:
  --windows-user NAME    Windows account name (WSL only)
  --dropbox-home PATH    Dropbox root as seen from the current OS
  -h, --help             Show this help

Supported environments:
  - Ubuntu under WSL2
  - macOS

The script configures:
  - RESEARCH_ROOT -> Dropbox/Research
  - LARGE_ROOT -> Dropbox/ForShareLargeData
  - ~/src, ~/worktrees, ~/scratch
  - commands under ~/.local/bin

Dropbox paths are written directly to ~/.research_env. No ~/data-roots
indirection directory is created. Project-specific links are reconstructed by
each project's scripts/configure-workspace.sh.
USAGE
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --windows-user)
      [[ $# -ge 2 ]] || fail "--windows-user requires a value"
      WINDOWS_USER="$2"
      shift 2
      ;;
    --dropbox-home)
      [[ $# -ge 2 ]] || fail "--dropbox-home requires a value"
      DROPBOX_HOME="$2"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      fail "Unknown option: $1"
      ;;
  esac
done

PLATFORM="$(platform_name)"
[[ "$PLATFORM" != "unsupported" ]] || fail "Unsupported operating system: $(uname -s)"

find_macos_dropbox_home() {
  local candidates=()
  local candidate
  local existing
  local duplicate

  candidates+=("$HOME/Library/CloudStorage/Dropbox")
  candidates+=("$HOME/Dropbox")

  if [[ -d "$HOME/Library/CloudStorage" ]]; then
    while IFS= read -r candidate; do
      duplicate=false
      for existing in "${candidates[@]}"; do
        if [[ "$existing" == "$candidate" ]]; then
          duplicate=true
          break
        fi
      done
      [[ "$duplicate" == true ]] || candidates+=("$candidate")
    done < <(find "$HOME/Library/CloudStorage" -maxdepth 1 -type d -name 'Dropbox*' -print 2>/dev/null | sort)
  fi

  local matches=()
  for candidate in "${candidates[@]}"; do
    if [[ -d "$candidate/Research" && -d "$candidate/ForShareLargeData" ]]; then
      matches+=("$candidate")
    fi
  done

  if [[ ${#matches[@]} -eq 1 ]]; then
    printf '%s\n' "${matches[0]}"
    return 0
  fi

  if [[ ${#matches[@]} -gt 1 ]]; then
    echo "Multiple Dropbox roots contain both required directories:" >&2
    printf '  %s\n' "${matches[@]}" >&2
    echo "Rerun with --dropbox-home PATH." >&2
    return 1
  fi

  return 1
}

if [[ -z "$DROPBOX_HOME" ]]; then
  case "$PLATFORM" in
    linux)
      is_wsl || fail "Linux is supported only under WSL2 by this setup script."
      if [[ -z "$WINDOWS_USER" ]] && command -v cmd.exe >/dev/null 2>&1; then
        WINDOWS_USER="$(cmd.exe /C 'echo %USERNAME%' 2>/dev/null | tr -d '\r' | tail -n 1)"
      fi
      [[ -n "$WINDOWS_USER" ]] || fail "Could not detect the Windows user. Use --windows-user or --dropbox-home."
      DROPBOX_HOME="/mnt/c/Users/$WINDOWS_USER/Dropbox"
      ;;
    macos)
      DROPBOX_HOME="$(find_macos_dropbox_home || true)"
      [[ -n "$DROPBOX_HOME" ]] || fail "Could not identify the Dropbox root. Use --dropbox-home PATH."
      ;;
  esac
fi

RESEARCH_SOURCE="$DROPBOX_HOME/Research"
LARGE_SOURCE="$DROPBOX_HOME/ForShareLargeData"

[[ -d "$RESEARCH_SOURCE" ]] || fail "Dropbox Research directory was not found: $RESEARCH_SOURCE"
[[ -d "$LARGE_SOURCE" ]] || fail "Dropbox ForShareLargeData directory was not found: $LARGE_SOURCE"

mkdir -p "$HOME/src" "$HOME/worktrees" "$HOME/scratch" "$HOME/.local/bin"

# Safely remove the legacy indirection created by older versions. Only known
# symlinks are removed; unexpected files/directories are preserved and warned.
LEGACY_DATA_ROOTS="$HOME/data-roots"
if [[ -d "$LEGACY_DATA_ROOTS" && ! -L "$LEGACY_DATA_ROOTS" ]]; then
  for legacy_name in Research ForShareLargeData LocalLarge; do
    legacy_path="$LEGACY_DATA_ROOTS/$legacy_name"
    if [[ -L "$legacy_path" ]]; then
      rm -f "$legacy_path"
    elif [[ -e "$legacy_path" ]]; then
      warn "Legacy path is not a symlink and was preserved: $legacy_path"
    fi
  done
  if ! rmdir "$LEGACY_DATA_ROOTS" 2>/dev/null; then
    warn "Legacy directory remains because it is not empty: $LEGACY_DATA_ROOTS"
  fi
elif [[ -L "$LEGACY_DATA_ROOTS" ]]; then
  warn "Legacy ~/data-roots is itself a symlink and was preserved: $LEGACY_DATA_ROOTS"
fi

{
  echo '# Generated by research-dev-infra/scripts/setup-machine.sh'
  printf 'export DROPBOX_ROOT=%q\n' "$DROPBOX_HOME"
  printf 'export RESEARCH_ROOT=%q\n' "$RESEARCH_SOURCE"
  printf 'export LARGE_ROOT=%q\n' "$LARGE_SOURCE"
  printf 'export SRC_ROOT=%q\n' "$HOME/src"
  printf 'export WORKTREE_ROOT=%q\n' "$HOME/worktrees"
  printf 'export SCRATCH_ROOT=%q\n' "$HOME/scratch"
} > "$HOME/.research_env"

RC_FILE="$(shell_rc_file)"
ensure_line "$RC_FILE" '[ -f "$HOME/.research_env" ] && source "$HOME/.research_env"'
ensure_line "$RC_FILE" 'export PATH="$HOME/.local/bin:$PATH"'

for command_pair in \
  "new-project:new-project.sh" \
  "new-worktree:new-worktree.sh" \
  "remove-worktree:remove-worktree.sh" \
  "setup-workspace:setup-workspace.sh" \
  "research-doctor:doctor.sh" \
  "install-coding-agents:install-agents.sh" \
  "install-miniforge:install-miniforge.sh" \
  "analysis-smoke-test:analysis-smoke-test.sh" \
  "setup-vscode:setup-vscode.sh" \
  "setup-agent-defaults:setup-agent-defaults.sh" \
  "setup-emacs:setup-emacs.sh"
do
  command_name="${command_pair%%:*}"
  script_name="${command_pair#*:}"
  replace_symlink "$INFRA_ROOT/scripts/$script_name" "$HOME/.local/bin/$command_name"
done

# Remove only the obsolete command symlink created by this infra. Preserve a
# real file or unrelated symlink with the same name.
OLD_COMMAND="$HOME/.local/bin/setup-project-links"
if [[ -L "$OLD_COMMAND" ]]; then
  old_target="$(readlink "$OLD_COMMAND")"
  if [[ "$old_target" == *"/research-dev-infra/scripts/setup-project-links.sh" || "$old_target" == *"/research-dev-infra/scripts/setup-workspace.sh" ]]; then
    rm -f "$OLD_COMMAND"
  fi
fi

info "Machine setup completed"
echo "  Platform:                  $PLATFORM"
echo "  Dropbox root:              $DROPBOX_HOME"
echo "  RESEARCH_ROOT:             $RESEARCH_SOURCE"
echo "  LARGE_ROOT:                $LARGE_SOURCE"
echo "  Environment file:          $HOME/.research_env"
echo "  Shell startup file:        $RC_FILE"
echo
echo "Run: source '$RC_FILE'"
echo "Then: hash -r && research-doctor"
echo "Configure VS Code extensions: setup-vscode"
echo "Configure research-grade agent defaults: setup-agent-defaults"
echo "Optional Emacs editor: setup-emacs"
echo
echo "Project data and output links are defined in scripts/configure-workspace.sh."
echo "No ~/data-roots or global local-data directory is required."
echo
echo "After pulling a newer infra version, rerun this script once to register newly added commands."
